debug:
server:
  port: 9999
security:
  user:
    password: user
  ignored: /,/favicon.ico
oauth2:
  sso:
    loginPath: /dashboard/login
  client:
    tokenUri: http://localhost:8080/uaa/oauth/token
    authorizationUri: http://localhost:8080/uaa/oauth/authorize
    clientId: acme
    clientSecret: acmesecret
  resource:
    jwt:
      keyUri: http://localhost:8080/uaa/oauth/token_key
    id: openid
    serviceId: ${PREFIX:}resource
logging:
  level:
    org.springframework.security: DEBUG